-- Created by Shiva Krishna Komuravelly
-- Version: 0.0.0.1

-- foreign keys
ALTER TABLE DELIVERY_REQ_DETAILS DROP CONSTRAINT DELIVERY_REQUEST_FKEY_001;

ALTER TABLE DELIVERY_REQUEST DROP CONSTRAINT DELIVERY_REQUEST_STATUS_MASTER;

ALTER TABLE DELIVERY_REQUEST DROP CONSTRAINT DELIVERY_REQUEST_USERS;

ALTER TABLE DELIVERY_REQUEST DROP CONSTRAINT DELIVERY_REQUEST_ZIPCODE_COSTS;

ALTER TABLE DELIVERY_REQUEST DROP CONSTRAINT DELIVERY_REQ_STATUS_FKEY_001;

ALTER TABLE DELIVERY_REQUEST_STATUS DROP CONSTRAINT DEL_REQ_STATUS_FKEY_001;

ALTER TABLE FROM_TO_STATUS DROP CONSTRAINT FROM_TO_STATUS_FKEY_001;

ALTER TABLE FROM_TO_STATUS DROP CONSTRAINT FROM_TO_STATUS_FKEY_002;

ALTER TABLE ZIPCODE_COSTS DROP CONSTRAINT FROM_ZIPCODE_FKEY_001;

ALTER TABLE ROLE_PERMISSION DROP CONSTRAINT ROLE_PERMISSION_PERMISSION;

ALTER TABLE ROLE_PERMISSION DROP CONSTRAINT ROLE_PERMISSION_ROLE;

ALTER TABLE ZIPCODE_COSTS DROP CONSTRAINT TO_ZIPCODE_FKEY_002;

ALTER TABLE USER_ROLE_PERMISSION DROP CONSTRAINT USER_ROLE_PERMISSION_USERS;

ALTER TABLE USER_ROLE_PERMISSION DROP CONSTRAINT USER_ROLE_PERM_PKEY;





-- tables
DROP TABLE DELIVERY_REQUEST;
DROP TABLE DELIVERY_REQUEST_STATUS;
DROP TABLE DELIVERY_REQ_DETAILS;
DROP TABLE FROM_TO_STATUS;
DROP TABLE PERMISSION;
DROP TABLE ROLE;
DROP TABLE ROLE_PERMISSION;
DROP TABLE STATUS_MASTER;
DROP TABLE USERS;
DROP TABLE USER_ROLE_PERMISSION;
DROP TABLE ZIPCODE_COSTS;
DROP TABLE ZIPCODE_MASTER;



-- End of file.

